######################
#    PAXEL CONFIG    #
######################

# The CustomModelData value that the paxel's base tools (pickaxes,axes,shovels) use
# Used for assigning custom textures in resource packs
custom_model_data: 100

# If paxels should have their name written into the item's description (lore)
# The motivation for this is if players rename the paxels, this would distinguish them
# from regular tools without advanced tooltips or a resource pack
write_description: true

# Items from other plugins that should not be allowed to be crafted into a paxel
# Identified by a boolean namespaced key in the item's PersistentDataContainer
external_tool_keys:
- "hammer:is_hammer"

# [!] Experimental Feature - DISABLED by default
# Gives all paxels instant (+999) attack speed to fix a cosmetic bug
# where constant swapping results in the paxel always being in cooldown.
# Attack damage modifiers are removed from the tool to prevent it being used as a weapon.
# Only affects NEW paxels, will not convert existing ones!
experimental_attack_speed: false