name: Hammer
author: PoorgrammerDev
description: Adds a craftable hammer tool that digs in a 3x3 radius
version: '${project.version}'
main: io.github.poorgrammerdev.hammer.Hammer
api-version: '1.20'
commands:
  givehammer:
    usage: /givehammer <username> <type> [count] [damage]
    description: Give players hammers.
    permission: hammer.givehammer
    permission-message: You do not have permission to use this command.