#####################################################
# Activate or deactivate each module of the plugin. #
# Write "true" to enable or "false" to disable.     #
#####################################################
modules:
  # QuickReplant: Right click a fully grown crop to harvest it and replant it.
  # Holding a seed in your hand will replant that crop instead of the existing.
  quick_replant: true

  # CropCascade: Right click fully grown crops with a hoe to harvest them in an area.
  # Holding a seed in your offhand will replant that crop instead of the existing.
  crop_cascade: true

  # AutoPlanter: Dispensers can plant crops onto farmland
  # Dispensers can plant in a short range in a straight line directly in front of them.
  auto_planter: true

######################
# PLUGIN DEFINITIONS #
######################
# This maps placed crop blocks to their seed items and base blocks (the block they can be planted on).
# The format is:
# - ["CROP BLOCK", "SEED ITEM", "BASE BLOCK"]
# where CROP BLOCK is the placed block, SEED ITEM is the held item, and BASE BLOCK is the block the crop is planted on
# All of these values use Bukkit Material enum names, found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html (This link is valid as of 07 January 2024)
crop_definitions:
  - ["WHEAT", "WHEAT_SEEDS", "FARMLAND"]
  - ["CARROTS", "CARROT", "FARMLAND"]
  - ["POTATOES", "POTATO", "FARMLAND"]
  - ["BEETROOTS", "BEETROOT_SEEDS", "FARMLAND"]
  - ["NETHER_WART", "NETHER_WART", "SOUL_SAND"]

##################
# MODULE OPTIONS #
##################

# Defines the maximum area that each hoe type harvests/replants in.
# Values cannot be less than 1. If it is not specified, the default is 1.
# It is not recommended to set these values too high for both balance and performance reasons.
# Measured in blocks out in each direction from the center
cascade_radii:
  wooden_hoe: 2
  golden_hoe: 3
  stone_hoe: 3
  iron_hoe: 5
  diamond_hoe: 7
  netherite_hoe: 10

# When using CropCascade, the hoe is left at a durability of 1 instead of breaking.
cascade_preserve_hoe: true

# CropCascade will stop if the seeds in the offhand run out.
# If disabled, it will continue, replacing the remaining crops with themselves as if you held nothing in the offhand.
cascade_seed_cancel: true

# How far (in blocks) can a dispenser can plant a crop
# Value cannot be less than 1. If it is not specified, the default is 4.
auto_planter_max_range: 4

# When there is exactly one seed left in the dispenser, it cannot be detected by normal means.
# A workaround is used to delay the planting by one tick. Proper checks are in place and should prevent any exploits.
# However, if an exploit is found and abused through this system, you can disable it here.
# With the system disabled, dispensers will not fire the last seed item in their inventory.
auto_planter_allow_workaround: true